services:
  # application service
  app:
    build: .
    container_name: app
    # .env файл подхватится автоматически (если есть)
    env_file: .env
    # Передаём DB_TYPE и прочие конфигурации в контейнер
    environment:
      - DB_TYPE=${DB_TYPE}
    #ports:
    #  - "8000:8000"
    networks:
      - main

  # nginx proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl.crt:/etc/nginx/ssl/ssl.crt:ro
      - ./nginx/ssl.key:/etc/nginx/ssl/ssl.key:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - main

networks:
  main:
    driver: bridge
