name: test 4

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start PostgreSQL
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          docker compose -f docker-compose.postgres.yaml up -d

      # üü¶ –û–∂–∏–¥–∞–Ω–∏–µ –∑–∞–ø—É—Å–∫–∞ –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞ Postgres
      - name: Wait for DB
        run: |
          for i in {1..20}; do
            docker exec $(docker ps -q --filter "name=postgres") \
              pg_isready -U "${{ secrets.DB_USER }}" && break
            sleep 2
          done

      # üü¶ –£—Å—Ç–∞–Ω–æ–≤–∫–∞ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–µ–π –∏ –∑–∞–ø—É—Å–∫ unittest
      - name: Run tests
        run: |
          pip install psycopg2-binary
          python -m unittest discover -s tests/integration -p "test_4.py"
