name: main

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  test-1:
    runs-on: ubuntu-latest

    env:
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      DB_TYPE: "fake" 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run unittest tests
        run: python -m unittest discover -s tests -p "test_1.py"
  
  test-4:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ vars.DB_PASSWORD }}
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Patch compose file for CI
        run: |
          sed -i '/networks:/,/main:/d' docker-compose.postgres.yml
          sed -i 's/- main//g' docker-compose.postgres.yml


      - name: Start PostgreSQL
        run: |
          docker compose -f docker-compose.postgres.yml up -d


      # üü¶ –û–∂–∏–¥–∞–Ω–∏–µ –∑–∞–ø—É—Å–∫–∞ –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞ Postgres
      - name: Wait for Postgres
        run: |
          docker ps
          SERVICE_NAME=db 
          for i in {1..40}; do
            docker compose -f docker-compose.postgres.yml exec -T $SERVICE_NAME pg_isready -U "${{ secrets.POSTGRES_USER }}" && break
            echo "Waiting for Postgres..."
            sleep 2
          done

      # üü¶ –£—Å—Ç–∞–Ω–æ–≤–∫–∞ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–µ–π –∏ –∑–∞–ø—É—Å–∫ unittest
      - name: Run tests
        run: |

          pip install psycopg2-binary
          python -m unittest discover -s tests -p "test_4.py"
