name: main

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  test-1:
    runs-on: ubuntu-latest

    env:
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      DB_TYPE: "fake" 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run unittest tests
        run: python -m unittest discover -s tests -p "test_1.py"
  
  test-4:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start PostgreSQL
        env:
          DB_USER: ${{ secrets.POSTGRES_USER }}
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_NAME: ${{ secrets.POSTGRES_DB }}
        run: |
          docker compose -f docker-compose.postgres.yml up -d

      # üü¶ –û–∂–∏–¥–∞–Ω–∏–µ –∑–∞–ø—É—Å–∫–∞ –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞ Postgres
      - name: Wait for DB
        run: |
          for i in {1..20}; do
            docker exec $(docker ps -q --filter "name=postgres") \
              pg_isready -U "${{ secrets.POSTGRES_USER }}" && break
            sleep 2
          done

      # üü¶ –£—Å—Ç–∞–Ω–æ–≤–∫–∞ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–µ–π –∏ –∑–∞–ø—É—Å–∫ unittest
      - name: Run tests
        run: |
          pip install psycopg2-binary
          python -m unittest discover -s tests -p "test_4.py"
