name: main

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  test-1:
    runs-on: ubuntu-latest
    environment: secret
    env:
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      DB_TYPE: "fake" 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run unittest tests
        run: python -m unittest discover -s tests -p "test_1.py"
  
  test-4:
    runs-on: ubuntu-latest
    environment: secret
    env:
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
    steps:
      - uses: actions/checkout@v4
      
      - name: Patch compose file for CI
        run: |
          sed -i '/networks:/,/main:/d' docker-compose.postgres.yml
          sed -i 's/- main//g' docker-compose.postgres.yml


      - name: Start PostgreSQL
        run: |
          docker compose -f docker-compose.postgres.yml up -d


      # üü¶ –û–∂–∏–¥–∞–Ω–∏–µ –∑–∞–ø—É—Å–∫–∞ –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞ Postgres
      - name: Wait for Postgres
        run: |
          docker ps
          SERVICE_NAME=db 
          for i in {1..40}; do
            docker compose -f docker-compose.postgres.yml exec -T $SERVICE_NAME pg_isready -U "${{ secrets.POSTGRES_USER }}" && break
            echo "Waiting for Postgres..."
            sleep 2
          done
      - name: Get PostgreSQL Container IP Address
        id: get_ip
        run: |
          # –ü–æ–ª—É—á–∞–µ–º IP-–∞–¥—Ä–µ—Å –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞ –ø–æ –µ–≥–æ –∏–º–µ–Ω–∏ –∏ —Å–æ—Ö—Ä–∞–Ω—è–µ–º –µ–≥–æ –≤ –ø–µ—Ä–µ–º–µ–Ω–Ω—É—é –æ–∫—Ä—É–∂–µ–Ω–∏—è GITHUB_OUTPUT
          DB_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ci_postgres_db)
          echo "POSTGRES_HOST=$DB_IP" >> $GITHUB_OUTPUT
          echo "–ü–æ–ª—É—á–µ–Ω IP –∞–¥—Ä–µ—Å –ë–î: $DB_IP"
        # üü¶ –£—Å—Ç–∞–Ω–æ–≤–∫–∞ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–µ–π –∏ –∑–∞–ø—É—Å–∫ unittest
      - name: Run tests
        env:
          POSTGRES_HOST: ${{ steps.get_ip.outputs.POSTGRES_HOST }}
        run: |

          pip install psycopg2-binary
          python -m unittest discover -s tests -p "test_4.py"
