name: SAST

on:
  push:
  pull_request:

jobs:

  bandit:
    name: Bandit SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f screen -ll



  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

  horusec:
    name: Horusec SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Horusec CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/scripts/install-cli.sh | bash

      - name: Run Horusec scan
        run: |
          horusec start -p . --json-output-file horusec-report.json || true

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: horusec-report
          path: horusec-report.json
