name: SAST

on:
  push:
  pull_request:

jobs:

  bandit:
    name: Bandit SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f screen -ll



  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

  pysa:
    name: Pysa (Pyre) SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Pyre
        run: |
          pip install pyre-check

      - name: Initialize Pyre
        run: |
          pyre init

      - name: Run Pysa
        run: |
          pyre analyze --save-results-to pysa-results

      - name: Upload Pysa report
        uses: actions/upload-artifact@v4
        with:
          name: pysa-results
          path: pysa-results
